// Disclaimer.tsx — aviso legal sobrio y persistente, en todas las páginas.
// Antes iba ENCIMA de la navegación: en móvil ocupaba cuatro líneas de la
// primera pantalla, antes incluso del nombre del producto. Ahora es el pie
// de página — sigue en cada pantalla, legible, sin competir con el contenido.
import Link from "next/link";
import { getT } from "@/lib/locale";

export async function Disclaimer() {
  const { t } = await getT();
  return (
    <footer className="mx-auto mt-10 max-w-7xl border-t border-border-subtle px-4 py-4 text-center text-[11px] leading-snug text-text-tertiary sm:px-6">
      {t(
        "Contenido informativo generado por un sistema automatizado. No constituye asesoramiento de inversión ni una recomendación personalizada. Rendimiento pasado no garantiza resultados futuros.",
        "Informational content generated by an automated system. It is not investment advice or a personalised recommendation. Past performance does not guarantee future results.",
      )}
      <span className="mt-2 block">
        {t("También:", "Also:")}{" "}
        <Link href="/largo-plazo" className="underline decoration-dotted hover:text-foreground">
          {t("ranking de calidad a largo plazo", "long-term quality ranking")}
        </Link>
      </span>
    </footer>
  );
}
